import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Wind, GithubLogo, MagnifyingGlass } from "@phosphor-icons/react";
import { Form, Nav } from "react-bootstrap";
import Searchbar from "@/components/Searchbar";
import Menubar from "@/components/Menubar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Aeris</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div>
					<Menubar />
				</div>
				<div className={styles.center}>
					<div className={styles.textSection}>
						<h3>Welcome to your air quality monitoring system.</h3>
						<h4>start by searching any portuguese city</h4>
					</div>
				</div>
			</main>
		</>
	);
}
